apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-config-server-db-pvc
  namespace: ai-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
