package contract

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// dartString quotes and escapes a string as a Dart string literal.
func dartString(value string) string {
	escaped := strings.ReplaceAll(value, "\\", "\\\\")
	escaped = strings.ReplaceAll(escaped, "'", "\\'")
	return "'" + escaped + "'"
}

// dartLiteral renders a Go value (decoded with json.UseNumber) into a Dart literal.
func dartLiteral(value any) string {
	return dartLiteralAt(value, 0)
}

func dartLiteralAt(value any, indent int) string {
	if value == nil {
		return "null"
	}
	switch v := value.(type) {
	case bool:
		if v {
			return "true"
		}
		return "false"
	case string:
		return dartString(v)
	case json.Number:
		if v == "" {
			return "null"
		}
		return v.String()
	case []any:
		items := make([]string, len(v))
		for i, item := range v {
			items[i] = dartLiteralAt(item, indent)
		}
		return "[" + strings.Join(items, ", ") + "]"
	case map[string]any:
		keys := make([]string, 0, len(v))
		for key := range v {
			keys = append(keys, key)
		}
		sort.Strings(keys)
		if len(keys) == 0 {
			return "{}"
		}
		childIndent := strings.Repeat(" ", indent+2)
		lines := []string{"{"}
		for _, key := range keys {
			lines = append(lines, fmt.Sprintf("%s%s: %s,", childIndent, dartString(key), dartLiteralAt(v[key], indent+2)))
		}
		lines = append(lines, strings.Repeat(" ", indent)+"}")
		return strings.Join(lines, "\n")
	default:
		return fmt.Sprintf("%v", v)
	}
}

// RenderDartContract renders the Dart code from runtime-contract.json bytes.
func RenderDartContract(contractData []byte) ([]byte, error) {
	decoder := json.NewDecoder(bytes.NewReader(contractData))
	decoder.UseNumber()

	var contract RuntimeContract
	if err := decoder.Decode(&contract); err != nil {
		return nil, fmt.Errorf("failed to decode contract JSON: %w", err)
	}

	var sb strings.Builder
	sb.WriteString("// Code generated by rcf-config. DO NOT EDIT.\n\n")
	sb.WriteString("class RuntimeConfigField {\n")
	sb.WriteString("  final String canonical;\n")
	sb.WriteString("  final String type;\n")
	sb.WriteString("  final String scope;\n")
	sb.WriteString("  final String env;\n")
	sb.WriteString("  final String apiJson;\n")
	sb.WriteString("  final String launchArgument;\n")
	sb.WriteString("  final String rosParameter;\n")
	sb.WriteString("  final bool secret;\n")
	sb.WriteString("  final Object? defaultValue;\n")
	sb.WriteString("  final List<Object?> enumValues;\n")
	sb.WriteString("  final num? minimum;\n")
	sb.WriteString("  final num? maximum;\n\n")
	sb.WriteString("  const RuntimeConfigField({\n")
	sb.WriteString("    required this.canonical,\n")
	sb.WriteString("    required this.type,\n")
	sb.WriteString("    required this.scope,\n")
	sb.WriteString("    required this.env,\n")
	sb.WriteString("    required this.apiJson,\n")
	sb.WriteString("    required this.launchArgument,\n")
	sb.WriteString("    required this.rosParameter,\n")
	sb.WriteString("    required this.secret,\n")
	sb.WriteString("    required this.defaultValue,\n")
	sb.WriteString("    required this.enumValues,\n")
	sb.WriteString("    required this.minimum,\n")
	sb.WriteString("    required this.maximum,\n")
	sb.WriteString("  });\n")
	sb.WriteString("}\n\n")
	sb.WriteString(fmt.Sprintf("const runtimeConfigSchemaVersion = %s;\n\n", dartString(contract.SchemaVersion)))
	sb.WriteString("const runtimeConfigFields = <String, RuntimeConfigField>{\n")

	for _, field := range contract.Fields {
		sb.WriteString(fmt.Sprintf("  %s: RuntimeConfigField(\n", dartString(field.Canonical)))
		sb.WriteString(fmt.Sprintf("    canonical: %s,\n", dartString(field.Canonical)))
		sb.WriteString(fmt.Sprintf("    type: %s,\n", dartString(field.Type)))
		sb.WriteString(fmt.Sprintf("    scope: %s,\n", dartString(field.Scope)))
		sb.WriteString(fmt.Sprintf("    env: %s,\n", dartString(field.Env)))
		sb.WriteString(fmt.Sprintf("    apiJson: %s,\n", dartString(field.APIJson)))
		sb.WriteString(fmt.Sprintf("    launchArgument: %s,\n", dartString(field.LaunchArgument)))
		sb.WriteString(fmt.Sprintf("    rosParameter: %s,\n", dartString(field.ROSParameter)))
		secretStr := "false"
		if field.Secret {
			secretStr = "true"
		}
		sb.WriteString(fmt.Sprintf("    secret: %s,\n", secretStr))
		sb.WriteString(fmt.Sprintf("    defaultValue: %s,\n", dartLiteralAt(field.Default, 4)))
		sb.WriteString(fmt.Sprintf("    enumValues: %s,\n", dartLiteral(field.Enum)))
		sb.WriteString(fmt.Sprintf("    minimum: %s,\n", dartLiteral(field.Minimum)))
		sb.WriteString(fmt.Sprintf("    maximum: %s,\n", dartLiteral(field.Maximum)))
		sb.WriteString("  ),\n")
	}

	sb.WriteString("};\n")

	return []byte(sb.String()), nil
}

// GenerateDartArtifact renders and writes the Dart contract file or checks if it is up to date.
// Returns (upToDate, error). When checkOnly is false, it writes the file if out of date.
func GenerateDartArtifact(contractFile, targetDartFile string, checkOnly bool) (bool, error) {
	contractData, err := os.ReadFile(contractFile)
	if err != nil {
		return false, fmt.Errorf("failed to read contract file %s: %w", contractFile, err)
	}

	content, err := RenderDartContract(contractData)
	if err != nil {
		return false, err
	}

	var currentContent []byte
	if current, err := os.ReadFile(targetDartFile); err == nil {
		currentContent = current
	}

	upToDate := bytes.Equal(content, currentContent)
	if upToDate {
		return true, nil
	}

	if checkOnly {
		return false, nil
	}

	if err := os.MkdirAll(filepath.Dir(targetDartFile), 0755); err != nil {
		return false, fmt.Errorf("failed to create directory for %s: %w", targetDartFile, err)
	}

	if err := os.WriteFile(targetDartFile, content, 0644); err != nil {
		return false, fmt.Errorf("failed to write %s: %w", targetDartFile, err)
	}

	return false, nil
}
