package handler

import (
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"reflect"
	"strconv"
	"strings"

	"github.com/gin-gonic/gin"
	"gorm.io/gorm"

	"ai-config-server/database"
	"ai-config-server/database/models"
)

// GetConfigFile GET /api/v1/configs/:id/files/:filename
// 관리자용: 활성 여부와 무관하게 특정 설정 ID의 파일(.env 등)을 조회합니다.
func GetConfigFile(c *gin.Context) {
	id, err := strconv.Atoi(c.Param("id"))
	if err != nil {
		LogAndRespondError(c, http.StatusBadRequest, "올바르지 않은 ID 형식입니다.", err)
		return
	}
	filename := c.Param("filename")

	var config models.RoboClawConfig
	if err := database.DB.First(&config, id).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			LogAndRespondError(c, http.StatusNotFound, "해당 설정을 찾을 수 없습니다.", err)
		} else {
			LogAndRespondError(c, http.StatusInternalServerError, "설정 파일을 조회하는 중 오류가 발생했습니다.", err)
		}
		return
	}
	applyButlerPathDefaults(&config)

	content, ok := buildConfigFileContent(&config, filename)
	if !ok {
		LogAndRespondError(c, http.StatusNotFound, "요청한 파일명을 찾을 수 없습니다. (지원: .env, ROBOT.md, SKILLS.md, TROUBLESHOOTING.md, ROBOT_LIMITS.json)", nil)
		return
	}

	respondFile(c, filename, content)
}

// buildConfigFileContent는 설정 레코드로부터 요청된 파일명에 해당하는 콘텐츠를 생성합니다.
func buildConfigFileContent(cfg *models.RoboClawConfig, filename string) ([]byte, bool) {
	switch filename {
	case ".env":
		return []byte(generateEnvContent(cfg)), true
	case "ROBOT.md":
		return []byte(cfg.SoulContent), true
	case "SKILLS.md":
		return []byte(cfg.SkillsContent), true
	case "TROUBLESHOOTING.md":
		return []byte(cfg.TroubleshootingContent), true
	case "ROBOT_LIMITS.json":
		return []byte(cfg.LimitsContent), true
	default:
		return nil, false
	}
}

// generateEnvContent는 DB 레코드를 기반으로 .env 파일 포맷 문자열을 동적 생성합니다.
func generateEnvContent(cfg *models.RoboClawConfig) string {
	// dotenv는 줄바꿈을 값의 끝으로 인식하므로, 관리 화면에 입력된 개행이
	// 새로운 환경변수로 해석되지 않도록 생성 전에 안전한 literal로 변환한다.
	// 복사본만 정규화해 DB에 저장된 원문은 보존한다.
	safeCfg := *cfg
	if safeCfg.System1ConfThresholdsJson != "" {
		var compact bytes.Buffer
		if err := json.Compact(&compact, []byte(safeCfg.System1ConfThresholdsJson)); err == nil {
			safeCfg.System1ConfThresholdsJson = compact.String()
		}
	}
	value := reflect.ValueOf(&safeCfg).Elem()
	for i := 0; i < value.NumField(); i++ {
		field := value.Field(i)
		if field.Kind() == reflect.String && field.CanSet() {
			field.SetString(strings.ReplaceAll(strings.ReplaceAll(field.String(), "\r", "\\r"), "\n", "\\n"))
		}
	}
	cfg = &safeCfg
	applyButlerPathDefaults(cfg)

	var sb strings.Builder

	sb.WriteString("# Generated by ai-config-server\n")
	fmt.Fprintf(&sb, "# Robot: %s | Environment: %s\n\n", cfg.RobotName, cfg.Environment)

	fmt.Fprintf(&sb, "ROS_DOMAIN_ID=%d\n\n", cfg.RosDomainId)
	fmt.Fprintf(&sb, "RC_AGENT_ID=%s\n\n", cfg.AgentId)

	fmt.Fprintf(&sb, "RC_LLM_PROVIDER=%s\n", cfg.LlmProvider)
	fmt.Fprintf(&sb, "RC_LLM_MODEL=%s\n\n", cfg.LlmModel)

	if cfg.AzureOpenaiEndpoint != "" {
		fmt.Fprintf(&sb, "AZURE_OPENAI_ENDPOINT=%s\n", cfg.AzureOpenaiEndpoint)
	}
	if cfg.AzureOpenaiApiKey != "" {
		fmt.Fprintf(&sb, "AZURE_OPENAI_API_KEY=%s\n", cfg.AzureOpenaiApiKey)
	}
	if cfg.OpenaiApiKey != "" {
		fmt.Fprintf(&sb, "OPENAI_API_KEY=%s\n", cfg.OpenaiApiKey)
	}
	if cfg.AnthropicApiKey != "" {
		fmt.Fprintf(&sb, "ANTHROPIC_API_KEY=%s\n", cfg.AnthropicApiKey)
	}
	sb.WriteString("\n")

	if cfg.LlmProvider == "ollama" {
		if cfg.OllamaBaseUrl != "" {
			fmt.Fprintf(&sb, "RC_OLLAMA_BASE_URL=%s\n", cfg.OllamaBaseUrl)
		}
		if cfg.OllamaOptionsJson != "" {
			fmt.Fprintf(&sb, "RC_OLLAMA_OPTIONS_JSON=%s\n", cfg.OllamaOptionsJson)
		}
		sb.WriteString("\n")
	}

	fmt.Fprintf(&sb, "RC_ENABLE_RAG=%t\n", cfg.EnableRag)
	if cfg.LlmEmbeddingProvider != "" {
		fmt.Fprintf(&sb, "RC_LLM_EMBEDDING_PROVIDER=%s\n", cfg.LlmEmbeddingProvider)
	}
	if cfg.LlmEmbeddingModel != "" {
		fmt.Fprintf(&sb, "RC_LLM_EMBEDDING_MODEL=%s\n", cfg.LlmEmbeddingModel)
	}
	if cfg.LlmEmbeddingBaseUrl != "" {
		fmt.Fprintf(&sb, "RC_LLM_EMBEDDING_BASE_URL=%s\n", cfg.LlmEmbeddingBaseUrl)
	}
	if cfg.LlmEmbeddingApiKey != "" {
		fmt.Fprintf(&sb, "RC_LLM_EMBEDDING_API_KEY=%s\n", cfg.LlmEmbeddingApiKey)
	}
	if cfg.RagVectorBackend != "" {
		fmt.Fprintf(&sb, "RC_RAG_VECTOR_BACKEND=%s\n", cfg.RagVectorBackend)
	}
	if cfg.QdrantUrl != "" {
		fmt.Fprintf(&sb, "QDRANT_URL=%s\n", cfg.QdrantUrl)
	}
	if cfg.QdrantApiKey != "" {
		fmt.Fprintf(&sb, "QDRANT_API_KEY=%s\n", cfg.QdrantApiKey)
	}
	if cfg.QdrantCollection != "" {
		fmt.Fprintf(&sb, "RC_QDRANT_COLLECTION=%s\n", cfg.QdrantCollection)
	}
	fmt.Fprintf(&sb, "RC_RAG_TOP_K=%d\n", cfg.RagTopK)
	fmt.Fprintf(&sb, "RC_RAG_SCORE_THRESHOLD=%g\n", cfg.RagScoreThreshold)
	fmt.Fprintf(&sb, "RC_QDRANT_TIMEOUT_SEC=%g\n", cfg.QdrantTimeoutSec)
	fmt.Fprintf(&sb, "RC_RAG_LOCAL_MIRROR=%t\n", cfg.RagLocalMirror)
	fmt.Fprintf(&sb, "RC_ENABLE_SKILL_LEARNING=%t\n", cfg.EnableSkillLearning)
	fmt.Fprintf(&sb, "RC_SKILL_LEARNING_SUCCESS_SAMPLE_RATE=%g\n", cfg.SkillLearningSuccessSampleRate)
	fmt.Fprintf(&sb, "RC_SKILL_LEARNING_REFLECT_INTERVAL_SEC=%d\n\n", cfg.SkillLearningReflectIntervalSec)

	// 태스크 큐 / 복합 명령 자동 분해 설정
	fmt.Fprintf(&sb, "RC_TASK_QUEUE_MAX_SIZE=%d\n", cfg.TaskQueueMaxSize)
	fmt.Fprintf(&sb, "RC_LLM_FAIL_FAST=%t\n", cfg.LlmFailFast)
	fmt.Fprintf(&sb, "RC_STRICT_CONFIG=%t\n", cfg.StrictConfig)
	fmt.Fprintf(&sb, "RC_ENABLE_TASK_DECOMPOSITION=%t\n", cfg.EnableTaskDecomposition)
	fmt.Fprintf(&sb, "RC_TASK_DECOMPOSITION_MAX_STEPS=%d\n", cfg.TaskDecompositionMaxSteps)
	fmt.Fprintf(&sb, "RC_TASK_STEP_MAX_RETRIES=%d\n", cfg.TaskStepMaxRetries)
	fmt.Fprintf(&sb, "RC_TASK_DECOMPOSITION_WAIT_MARGIN_CAP_SEC=%g\n\n", cfg.TaskDecompositionWaitMarginCapSec)

	fmt.Fprintf(&sb, "ENABLE_DISCORD=%t\n", cfg.EnableDiscord)
	fmt.Fprintf(&sb, "ENABLE_TELEGRAM=%t\n", cfg.EnableTelegram)
	fmt.Fprintf(&sb, "ENABLE_SLACK=%t\n", cfg.EnableSlack)
	fmt.Fprintf(&sb, "ENABLE_GRPC=%t\n", cfg.EnableGrpc)
	fmt.Fprintf(&sb, "ROBO_CLAW_GRPC_PORT=%d\n", cfg.GrpcPort)
	fmt.Fprintf(&sb, "USE_GRPC=%t\n", cfg.UseGrpc)
	fmt.Fprintf(&sb, "ENABLE_GRPC_CLIENT=%t\n", cfg.EnableGrpcClient)
	if cfg.GrpcTargetHost != "" {
		fmt.Fprintf(&sb, "GRPC_TARGET_HOST=%s\n", cfg.GrpcTargetHost)
	} else {
		sb.WriteString("GRPC_TARGET_HOST=127.0.0.1\n")
	}
	if cfg.GrpcTargetPort > 0 {
		fmt.Fprintf(&sb, "GRPC_TARGET_PORT=%d\n", cfg.GrpcTargetPort)
	} else {
		sb.WriteString("GRPC_TARGET_PORT=50052\n")
	}
	fmt.Fprintf(&sb, "GRPC_TARGET_PEERS_JSON=%s\n\n", cfg.GrpcTargetPeersJson)
	if cfg.GrpcPeerToken != "" {
		fmt.Fprintf(&sb, "GRPC_PEER_TOKEN=%s\n", cfg.GrpcPeerToken)
	}

	if cfg.DiscordBotToken != "" {
		fmt.Fprintf(&sb, "DISCORD_BOT_TOKEN=%s\n", cfg.DiscordBotToken)
	}
	if cfg.SlackAppToken != "" {
		fmt.Fprintf(&sb, "SLACK_APP_TOKEN=%s\n", cfg.SlackAppToken)
	}
	if cfg.SlackBotToken != "" {
		fmt.Fprintf(&sb, "SLACK_BOT_TOKEN=%s\n", cfg.SlackBotToken)
	}
	if cfg.TelegramBotToken != "" {
		fmt.Fprintf(&sb, "TELEGRAM_BOT_TOKEN=%s\n\n", cfg.TelegramBotToken)
	}

	// HTTP API 보안 설정
	if cfg.HttpHost != "" {
		fmt.Fprintf(&sb, "RC_HTTP_HOST=%s\n", cfg.HttpHost)
	}
	if cfg.HttpPort != 0 {
		fmt.Fprintf(&sb, "RC_HTTP_PORT=%d\n", cfg.HttpPort)
	}
	if cfg.HttpReadonlyToken != "" {
		fmt.Fprintf(&sb, "RC_HTTP_READONLY_TOKEN=%s\n", cfg.HttpReadonlyToken)
	}
	if cfg.HttpControlToken != "" {
		fmt.Fprintf(&sb, "RC_HTTP_CONTROL_TOKEN=%s\n", cfg.HttpControlToken)
	}
	if cfg.HttpAllowedCidrsJson != "" && cfg.HttpAllowedCidrsJson != "[]" {
		fmt.Fprintf(&sb, "RC_HTTP_ALLOWED_CIDRS_JSON=%s\n", cfg.HttpAllowedCidrsJson)
	}
	if cfg.HttpRateLimitPerMinute != 0 {
		fmt.Fprintf(&sb, "RC_HTTP_RATE_LIMIT_PER_MINUTE=%d\n", cfg.HttpRateLimitPerMinute)
	}
	if cfg.HttpAllowedSkillsJson != "" && cfg.HttpAllowedSkillsJson != "[]" {
		fmt.Fprintf(&sb, "RC_HTTP_ALLOWED_SKILLS_JSON=%s\n", cfg.HttpAllowedSkillsJson)
	}
	if cfg.HttpBlockedSkillsJson != "" && cfg.HttpBlockedSkillsJson != "[]" {
		fmt.Fprintf(&sb, "RC_HTTP_BLOCKED_SKILLS_JSON=%s\n", cfg.HttpBlockedSkillsJson)
	}
	sb.WriteString("\n")

	// Dashboard 웹 노드 설정 (HTTP 채널 포트 8080과 별개)
	if cfg.DashboardHost != "" {
		fmt.Fprintf(&sb, "RC_DASHBOARD_HOST=%s\n", cfg.DashboardHost)
	}
	if cfg.DashboardPort != 0 {
		fmt.Fprintf(&sb, "RC_DASHBOARD_PORT=%d\n", cfg.DashboardPort)
	}
	sb.WriteString("\n")

	// MCP(Model Context Protocol) 서버 연동 설정
	fmt.Fprintf(&sb, "RC_ENABLE_MCP=%t\n", cfg.EnableMcp)
	if cfg.McpServersJson != "" && cfg.McpServersJson != "[]" {
		fmt.Fprintf(&sb, "RC_MCP_SERVERS_JSON=%s\n", cfg.McpServersJson)
	}
	sb.WriteString("\n")

	if cfg.AgentWorkspaceDir != "" {
		fmt.Fprintf(&sb, "RC_AGENT_WORKSPACE_DIR=%s\n", cfg.AgentWorkspaceDir)
	}
	if cfg.ButlerScriptsDir != "" {
		fmt.Fprintf(&sb, "RC_BUTLER_SCRIPTS_DIR=%s\n", cfg.ButlerScriptsDir)
	}
	if cfg.ButlerSourceDir != "" {
		fmt.Fprintf(&sb, "RC_BUTLER_SOURCE_DIR=%s\n", cfg.ButlerSourceDir)
	}
	if cfg.MemoryDir != "" {
		fmt.Fprintf(&sb, "RC_MEMORY_DIR=%s\n", cfg.MemoryDir)
	}
	if cfg.ConfigDir != "" {
		fmt.Fprintf(&sb, "RC_CONFIG_DIR=%s\n", cfg.ConfigDir)
	}
	if cfg.SystemPromptFile != "" {
		fmt.Fprintf(&sb, "RC_SYSTEM_PROMPT_FILE=%s\n", cfg.SystemPromptFile)
	}
	if cfg.RobotDescriptionFile != "" {
		fmt.Fprintf(&sb, "RC_ROBOT_DESCRIPTION_FILE=%s\n", cfg.RobotDescriptionFile)
	}
	fmt.Fprintf(&sb, "RC_DEBUG=%t\n", cfg.Debug)
	sb.WriteString("\n")

	// 카메라 / 비전 설정
	if cfg.CameraTopic != "" {
		fmt.Fprintf(&sb, "RC_CAMERA_TOPIC=%s\n", cfg.CameraTopic)
	}
	if cfg.GripperCameraTopic != "" {
		fmt.Fprintf(&sb, "RC_GRIPPER_CAMERA_TOPIC=%s\n", cfg.GripperCameraTopic)
	}
	if cfg.GripperDepthTopic != "" {
		fmt.Fprintf(&sb, "RC_GRIPPER_DEPTH_TOPIC=%s\n", cfg.GripperDepthTopic)
	}
	if cfg.GripperCameraInfoTopic != "" {
		fmt.Fprintf(&sb, "RC_GRIPPER_CAMERA_INFO_TOPIC=%s\n", cfg.GripperCameraInfoTopic)
	}
	if cfg.GripperPointcloudTopic != "" {
		fmt.Fprintf(&sb, "RC_GRIPPER_POINTCLOUD_TOPIC=%s\n", cfg.GripperPointcloudTopic)
	}
	fmt.Fprintf(&sb, "RC_USE_VISION=%t\n", cfg.UseVision)
	fmt.Fprintf(&sb, "RC_USE_GRIPPER_VISION=%t\n", cfg.UseGripperVision)
	if cfg.GripperVisionMaxInferenceHz > 0 {
		fmt.Fprintf(&sb, "RC_GRIPPER_VISION_MAX_INFERENCE_HZ=%g\n", cfg.GripperVisionMaxInferenceHz)
	}
	if cfg.VisionModelPath != "" {
		fmt.Fprintf(&sb, "RC_VISION_MODEL_PATH=%s\n", cfg.VisionModelPath)
	}
	sb.WriteString("\n")

	// 자가진단용 센서 토픽
	if cfg.LidarTopic != "" {
		fmt.Fprintf(&sb, "RC_LIDAR_TOPIC=%s\n", cfg.LidarTopic)
	}
	if cfg.ImuTopic != "" {
		fmt.Fprintf(&sb, "RC_IMU_TOPIC=%s\n", cfg.ImuTopic)
	}
	sb.WriteString("\n")

	// ── Maestro FleetControl outbound connector (contract v2.2.0) ──
	sb.WriteString("\n# ── Maestro FleetControl outbound connector ──\n")
	if cfg.MaestroIp != "" {
		fmt.Fprintf(&sb, "MAESTRO_IP=%s\n", cfg.MaestroIp)
	}
	fmt.Fprintf(&sb, "ROBOT_PORT=%d\n", cfg.RobotPort)
	if cfg.RobotId != "" {
		fmt.Fprintf(&sb, "ROBOT_ID=%s\n", cfg.RobotId)
	}
	if cfg.RobotSiteId != "" {
		fmt.Fprintf(&sb, "ROBOT_SITE_ID=%s\n", cfg.RobotSiteId)
	}
	if cfg.RobotMapId != "" {
		fmt.Fprintf(&sb, "ROBOT_MAP_ID=%s\n", cfg.RobotMapId)
	}
	if cfg.RobotMapVersion != "" {
		fmt.Fprintf(&sb, "ROBOT_MAP_VERSION=%s\n", cfg.RobotMapVersion)
	}
	fmt.Fprintf(&sb, "ROBOT_MAP_FRAME_ID=%s\n", cfg.RobotMapFrameId)
	fmt.Fprintf(&sb, "MAESTRO_DISCONNECT_POLICY=%s\n", cfg.MaestroDisconnectPolicy)
	fmt.Fprintf(&sb, "FLEET_HEARTBEAT_SEC=%g\n", cfg.FleetHeartbeatSec)
	fmt.Fprintf(&sb, "FLEET_COMMAND_JOURNAL_PATH=%s\n", cfg.FleetCommandJournalPath)
	if cfg.FleetControlTls {
		if cfg.FleetControlCaCert != "" {
			fmt.Fprintf(&sb, "FLEET_CONTROL_CA_CERT=%s\n", cfg.FleetControlCaCert)
		}
		if cfg.FleetControlClientCert != "" {
			fmt.Fprintf(&sb, "FLEET_CONTROL_CLIENT_CERT=%s\n", cfg.FleetControlClientCert)
		}
		if cfg.FleetControlClientKey != "" {
			fmt.Fprintf(&sb, "FLEET_CONTROL_CLIENT_KEY=%s\n", cfg.FleetControlClientKey)
		}
	}
	fmt.Fprintf(&sb, "FLEET_CONTROL_TLS=%t\n", cfg.FleetControlTls)

	// 로컬 마크다운 파일들의 위치는 디비 바인딩 후 생성될 경로를 가리키도록 설정
	sb.WriteString("RC_ROBOT_SOUL_FILE=config/ROBOT.md\n")
	if cfg.FleetSkillsGuideFile != "" {
		fmt.Fprintf(&sb, "RC_SKILLS_GUIDE_FILE=%s\n", cfg.FleetSkillsGuideFile)
	} else {
		sb.WriteString("RC_SKILLS_GUIDE_FILE=config/SKILLS.md\n")
	}
	sb.WriteString("RC_TROUBLESHOOTING_GUIDE_FILE=config/TROUBLESHOOTING.md\n")
	sb.WriteString("RC_ROBOT_LIMITS_FILE=config/ROBOT_LIMITS.json\n")

	// LangSmith 트레이싱 / 모니터링 설정
	sb.WriteString("\n# ── LangSmith 트레이싱 / 모니터링 (선택) ──\n")
	fmt.Fprintf(&sb, "LANGSMITH_TRACING=%t\n", cfg.LangsmithTracing)
	if cfg.LangsmithApiKey != "" {
		fmt.Fprintf(&sb, "LANGSMITH_API_KEY=%s\n", cfg.LangsmithApiKey)
	}
	if cfg.LangsmithProject != "" {
		fmt.Fprintf(&sb, "LANGSMITH_PROJECT=%s\n", cfg.LangsmithProject)
	}
	if cfg.LangsmithEndpoint != "" {
		fmt.Fprintf(&sb, "LANGSMITH_ENDPOINT=%s\n", cfg.LangsmithEndpoint)
	}
	if cfg.LangsmithWorkspaceId != "" {
		fmt.Fprintf(&sb, "LANGSMITH_WORKSPACE_ID=%s\n", cfg.LangsmithWorkspaceId)
	}

	// System 1 Fast Router 설정. 명시되지 않은 필드는 런타임 기본값과 일치시킨다.
	router := cfg.System1Router
	if router == "" {
		router = "rule"
	}
	fmt.Fprintf(&sb, "SYSTEM1_ROUTER=%s\n", router)
	fmt.Fprintf(&sb, "SYSTEM1_SHADOW=%t\n", cfg.System1Shadow)
	if cfg.System1ShadowLog != "" {
		fmt.Fprintf(&sb, "SYSTEM1_SHADOW_LOG=%s\n", cfg.System1ShadowLog)
	}
	scope := cfg.System1Scope
	if scope == "" {
		scope = "readonly"
	}
	fmt.Fprintf(&sb, "SYSTEM1_SCOPE=%s\n", scope)
	if cfg.System1Endpoint != "" {
		fmt.Fprintf(&sb, "SYSTEM1_ENDPOINT=%s\n", cfg.System1Endpoint)
	}
	provider := cfg.System1Provider
	if provider == "" {
		provider = "laya"
	}
	fmt.Fprintf(&sb, "SYSTEM1_PROVIDER=%s\n", provider)
	timeoutMs := cfg.System1TimeoutMs
	if timeoutMs <= 0 {
		timeoutMs = 300
	}
	fmt.Fprintf(&sb, "SYSTEM1_TIMEOUT_MS=%g\n", timeoutMs)
	if cfg.System1ConfThresholdsJson != "" {
		fmt.Fprintf(&sb, "SYSTEM1_CONF_THRESHOLDS_JSON=%s\n", cfg.System1ConfThresholdsJson)
	}
	if cfg.System1Skills != "" {
		fmt.Fprintf(&sb, "SYSTEM1_SKILLS=%s\n", cfg.System1Skills)
	}
	maxOptions := cfg.System1MaxOptions
	if maxOptions < 2 {
		maxOptions = 12
	}
	fmt.Fprintf(&sb, "SYSTEM1_MAX_OPTIONS=%d\n", maxOptions)
	if cfg.System1ApiKey != "" {
		fmt.Fprintf(&sb, "SYSTEM1_API_KEY=%s\n", cfg.System1ApiKey)
	}

	return sb.String()
}

// respondFile은 요청된 파일명 확장자에 따라 적합한 헤더 포맷을 지정해 Gin 응답을 수행합니다.
func respondFile(c *gin.Context, filename string, content []byte) {
	c.Header("Cache-Control", "no-store")
	switch filename {
	case ".env":
		c.Data(http.StatusOK, "text/plain; charset=utf-8", content)
	case "ROBOT.md", "SKILLS.md", "TROUBLESHOOTING.md":
		c.Data(http.StatusOK, "text/markdown; charset=utf-8", content)
	case "ROBOT_LIMITS.json":
		c.Data(http.StatusOK, "application/json; charset=utf-8", content)
	}
}
